baseURL = "http://aenjon.com"
languageCode = "zh-CN"
title = "态度的深度" 
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X
 
enableRobotsTXT = true
PaginatePath = "page"



## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "Aenjon"

[params]
  author = "Aenjon"
  subtitle = "全栈开发创业者"
  keywords = "java,c++,python,数据，算法，结构，架构"
  description = "数据分析、神经网络、人工智能、机器学习"
  busuanzi = true #启用不算子网页统计
  googleAd = "ca-pub-4031353640611810"  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "态度的高度的博客"
  name = "态度的高度的博客"
  url = "http://aenjon.com/"

[[params.links]]
  title = "博客转移"
  name = "CSDN"
  url = "https://blog.csdn.net/farphone"

## 侧边栏广告位
[[params.ads]]
  title = "知识付费"
  url = "https://blog.csdn.net/farphone"
  img = "http://aenjon.com/about/qrcode_for_weixin.jpg"


## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "your github repo" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单Tag","Category","Menu","Recent Post","Archives

[menu]



  [[menu.main]]
    identifier = "水滴"
    name = "水滴"
    url = "/tips/"
    weight = 2
  [[menu.main]]
    identifier = "tools"
    name = "工具"
    url = "/tools/"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "文档"
    url = "/archives/"
    weight = 4
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 5
  [[menu.main]]
    identifier = "categories"
    name = "类目"
    url = "/categories/"
    weight = 6
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 7
